### ISSUE TITLE
Is it possible to build / distribute app ?

### ISSUE THREAD

**Issue by znoue** [PaulLeCam/react-native-electron#15]
Hi and thank you for you work !

My app is working very well when i run it from command lines, but I can't find a way to distribute it. 

I tried to use prebuild binaries from here : https://github.com/electron/electron/releases and I spent several days trying to make it work playing with appropriate settings for react-native, but I can only get a blank electron window (index.html is displayed, and if I write something inside (in html) I can see it on screen, but not the react / react-native content)...

No success either with electron-forge, electron-builder, electron-packager...

Were you able to distribute an app with this extension ? If yes, could you explain how ?

Thank you again, cheers.

**Comment by PaulLeCam** [comment]
Hi, do you have any error message showing up in the console that could help explain the issue please?

**Comment by system32uwu** [comment]
Did you set up the project structure correctly?

Do you have your renderer.js file like the one in the [example](https://github.com/PaulLeCam/react-native-electron/blob/master/example/src/renderer.js)?

**Comment by system32uwu** [comment]
I just tried running the example and I'm getting a blank window as well. I installed electron, react-native and react-native-web, but it's not working as intended

**Comment by PaulLeCam** [comment]
The example now uses [Electron Forge](https://www.electronforge.io/) which can be used for packaging.
