### ISSUE TITLE
using with modules

### ISSUE THREAD

**Issue by elmcapp** [PaulLeCam/react-native-electron#17]
Will this package allow me to use modules like npm bonjour package which is a nodejs or electron module. I am looking for a solution that will allow me to use npm packages that are node support natively with react native

**Comment by PaulLeCam** [comment]
This package doesn't provide a built-in way to expose additional APIs, if I understand your question correctly?
You should be able to use Electron APIs directly to implement such behavior though.

**Comment by elmcapp** [comment]
Okay. I am using react native for macOS. The issue there is that I need to be able to use a package called bonjour which I can't get working with react. It does support electron but because I am not running electron and I am running react native macOS the package is not working. Hoping to find a solution to allow me to use additional api libraries

**Comment by PaulLeCam** [comment]
That sounds like something you should ask about in the React Native for macOS project.
